# Generated by Django 5.1.6 on 2025-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('prepared', 'Prepared Food'), ('groceries', 'Groceries'), ('produce', 'Fresh Produce')], max_length=20)),
                ('quantity', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('manual_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
