# Generated by Django 5.1.6 on 2025-02-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='food_type',
            field=models.CharField(choices=[('Prepared', 'Prepared Food'), ('Groceries', 'Groceries'), ('Produce', 'Fresh Produce')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=10),
        ),
    ]
