# Generated by Django 5.1.6 on 2025-02-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_donation_food_type_alter_donation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.FloatField(max_length=10),
        ),
    ]
