# Generated by Django 5.1.6 on 2025-02-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_donation_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Where the food is needed', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of request location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of request location', max_digits=9, null=True)),
                ('quantity', models.FloatField()),
                ('preferred_datetime', models.DateTimeField(help_text='Preferred date and time for delivery')),
                ('food_type', models.CharField(choices=[('Prepared', 'Prepared Food'), ('Groceries', 'Groceries'), ('Produce', 'Fresh Produce')], help_text='Type of food needed', max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Any special instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='manual_location',
        ),
        migrations.AddField(
            model_name='donation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
