# Generated by Django 5.1.6 on 2025-02-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_request_remove_donation_manual_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Latitude of request location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Longitude of request location', max_digits=9, null=True),
        ),
    ]
